name = "VelocityModRedirect" 
id = "velocitymodredirect"
version = "1.0-SNAPSHOT"
authors = ["Stevebell-sp"]
url = "https://github.com/Stevebell-sp/velocitymodredirect"
description = "A Velocity plugin to redirect players based on mods."

main = "com.stevebell.velocitymodredirect.ModList"
